/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionType = IDL.Variant({
  'shortAnswer' : IDL.Null,
  'multipleChoice' : IDL.Null,
});
export const QuizId = IDL.Text;
export const TopicId = IDL.Text;
export const QuizQuestionInput = IDL.Record({
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
  'questionType' : QuestionType,
  'quizId' : QuizId,
  'choices' : IDL.Vec(IDL.Text),
  'topicId' : TopicId,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
  'questionType' : QuestionType,
  'quizId' : QuizId,
  'choices' : IDL.Vec(IDL.Text),
  'topicId' : TopicId,
});
export const DifficultyLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const TopicInput = IDL.Record({
  'id' : TopicId,
  'subject' : IDL.Text,
  'prerequisites' : IDL.Vec(TopicId),
  'difficulty' : DifficultyLevel,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const TopicFact = IDL.Record({
  'id' : IDL.Nat,
  'factText' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'topicId' : TopicId,
});
export const Topic = IDL.Record({
  'id' : TopicId,
  'subject' : IDL.Text,
  'prerequisites' : IDL.Vec(TopicId),
  'difficulty' : DifficultyLevel,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'facts' : IDL.Vec(TopicFact),
});
export const TopicFactInput = IDL.Record({
  'factText' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'topicId' : TopicId,
});
export const UserId = IDL.Principal;
export const MasteryLevel = IDL.Variant({
  'needsWork' : IDL.Null,
  'mastered' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TopicProgress = IDL.Record({
  'userId' : UserId,
  'masteryLevel' : MasteryLevel,
  'lastUpdated' : Timestamp,
  'totalAttempts' : IDL.Nat,
  'correctCount' : IDL.Nat,
  'accuracyPercent' : IDL.Nat,
  'topicId' : TopicId,
});
export const GradeLevel = IDL.Variant({
  'highSchool' : IDL.Null,
  'elementary' : IDL.Null,
  'other' : IDL.Null,
  'middleSchool' : IDL.Null,
  'college' : IDL.Null,
});
export const StudentProfilePublic = IDL.Record({
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'gradeLevel' : GradeLevel,
  'preferredSubjects' : IDL.Vec(IDL.Text),
});
export const SessionId = IDL.Text;
export const QuizAttempt = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'studentAnswer' : IDL.Text,
  'isCorrect' : IDL.Bool,
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
  'questionId' : IDL.Nat,
  'sessionId' : SessionId,
  'quizId' : QuizId,
});
export const QuizSessionResult = IDL.Record({
  'userId' : UserId,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Timestamp,
  'sessionId' : SessionId,
  'correctCount' : IDL.Nat,
  'quizId' : QuizId,
});
export const MessageRole = IDL.Variant({
  'ai' : IDL.Null,
  'student' : IDL.Null,
});
export const MessageFeedback = IDL.Variant({
  'thumbsDown' : IDL.Null,
  'none' : IDL.Null,
  'thumbsUp' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'userId' : UserId,
  'role' : MessageRole,
  'feedback' : MessageFeedback,
  'timestamp' : Timestamp,
  'sessionId' : SessionId,
});
export const SessionSummary = IDL.Record({
  'keyTakeaways' : IDL.Vec(IDL.Text),
  'topic' : IDL.Text,
  'userId' : UserId,
  'durationSeconds' : IDL.Nat,
  'timestamp' : Timestamp,
  'sessionId' : SessionId,
});
export const SuggestedTopic = IDL.Record({
  'topicName' : IDL.Text,
  'topicId' : TopicId,
  'reason' : IDL.Text,
});
export const StudentProfileInput = IDL.Record({
  'name' : IDL.Text,
  'gradeLevel' : GradeLevel,
  'preferredSubjects' : IDL.Vec(IDL.Text),
});
export const SessionSummaryInput = IDL.Record({
  'keyTakeaways' : IDL.Vec(IDL.Text),
  'topic' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'sessionId' : SessionId,
});
export const SendMessageInput = IDL.Record({
  'content' : IDL.Text,
  'sessionId' : SessionId,
});
export const QuizAttemptInput = IDL.Record({
  'studentAnswer' : IDL.Text,
  'questionId' : IDL.Nat,
  'sessionId' : SessionId,
  'quizId' : QuizId,
});

export const idlService = IDL.Service({
  'addQuizQuestion' : IDL.Func([QuizQuestionInput], [QuizQuestion], []),
  'addTopic' : IDL.Func([TopicInput], [Topic], []),
  'addTopicFact' : IDL.Func([TopicFactInput], [TopicFact], []),
  'getAllMyProgress' : IDL.Func([], [IDL.Vec(TopicProgress)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(StudentProfilePublic)],
      ['query'],
    ),
  'getChatSessionHistory' : IDL.Func([], [IDL.Vec(SessionId)], ['query']),
  'getMyQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getMyTopicProgress' : IDL.Func(
      [TopicId],
      [IDL.Opt(TopicProgress)],
      ['query'],
    ),
  'getPrerequisiteTopics' : IDL.Func([TopicId], [IDL.Vec(Topic)], ['query']),
  'getQuizQuestion' : IDL.Func(
      [QuizId, IDL.Nat],
      [IDL.Opt(QuizQuestion)],
      ['query'],
    ),
  'getQuizQuestions' : IDL.Func([QuizId], [IDL.Vec(QuizQuestion)], ['query']),
  'getQuizSessionResult' : IDL.Func(
      [SessionId, QuizId],
      [QuizSessionResult],
      ['query'],
    ),
  'getSessionMessages' : IDL.Func(
      [SessionId],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getSessionSummary' : IDL.Func(
      [SessionId],
      [IDL.Opt(SessionSummary)],
      ['query'],
    ),
  'getSuggestedTopics' : IDL.Func([], [IDL.Vec(SuggestedTopic)], ['query']),
  'getTopic' : IDL.Func([TopicId], [IDL.Opt(Topic)], ['query']),
  'getTopicsBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Topic)], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(StudentProfilePublic)],
      ['query'],
    ),
  'getUserSessionSummaries' : IDL.Func(
      [],
      [IDL.Vec(SessionSummary)],
      ['query'],
    ),
  'listTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'recordTopicAttempt' : IDL.Func([TopicId, IDL.Bool], [TopicProgress], []),
  'saveCallerUserProfile' : IDL.Func([StudentProfileInput], [], []),
  'saveSessionSummary' : IDL.Func([SessionSummaryInput], [SessionSummary], []),
  'sendMessage' : IDL.Func([SendMessageInput], [ChatMessage], []),
  'setMessageFeedback' : IDL.Func([IDL.Nat, MessageFeedback], [IDL.Bool], []),
  'submitQuizAnswer' : IDL.Func([QuizAttemptInput], [QuizAttempt], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionType = IDL.Variant({
    'shortAnswer' : IDL.Null,
    'multipleChoice' : IDL.Null,
  });
  const QuizId = IDL.Text;
  const TopicId = IDL.Text;
  const QuizQuestionInput = IDL.Record({
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
    'questionType' : QuestionType,
    'quizId' : QuizId,
    'choices' : IDL.Vec(IDL.Text),
    'topicId' : TopicId,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
    'questionType' : QuestionType,
    'quizId' : QuizId,
    'choices' : IDL.Vec(IDL.Text),
    'topicId' : TopicId,
  });
  const DifficultyLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const TopicInput = IDL.Record({
    'id' : TopicId,
    'subject' : IDL.Text,
    'prerequisites' : IDL.Vec(TopicId),
    'difficulty' : DifficultyLevel,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const TopicFact = IDL.Record({
    'id' : IDL.Nat,
    'factText' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'topicId' : TopicId,
  });
  const Topic = IDL.Record({
    'id' : TopicId,
    'subject' : IDL.Text,
    'prerequisites' : IDL.Vec(TopicId),
    'difficulty' : DifficultyLevel,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'facts' : IDL.Vec(TopicFact),
  });
  const TopicFactInput = IDL.Record({
    'factText' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'topicId' : TopicId,
  });
  const UserId = IDL.Principal;
  const MasteryLevel = IDL.Variant({
    'needsWork' : IDL.Null,
    'mastered' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TopicProgress = IDL.Record({
    'userId' : UserId,
    'masteryLevel' : MasteryLevel,
    'lastUpdated' : Timestamp,
    'totalAttempts' : IDL.Nat,
    'correctCount' : IDL.Nat,
    'accuracyPercent' : IDL.Nat,
    'topicId' : TopicId,
  });
  const GradeLevel = IDL.Variant({
    'highSchool' : IDL.Null,
    'elementary' : IDL.Null,
    'other' : IDL.Null,
    'middleSchool' : IDL.Null,
    'college' : IDL.Null,
  });
  const StudentProfilePublic = IDL.Record({
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'gradeLevel' : GradeLevel,
    'preferredSubjects' : IDL.Vec(IDL.Text),
  });
  const SessionId = IDL.Text;
  const QuizAttempt = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'studentAnswer' : IDL.Text,
    'isCorrect' : IDL.Bool,
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
    'questionId' : IDL.Nat,
    'sessionId' : SessionId,
    'quizId' : QuizId,
  });
  const QuizSessionResult = IDL.Record({
    'userId' : UserId,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Timestamp,
    'sessionId' : SessionId,
    'correctCount' : IDL.Nat,
    'quizId' : QuizId,
  });
  const MessageRole = IDL.Variant({ 'ai' : IDL.Null, 'student' : IDL.Null });
  const MessageFeedback = IDL.Variant({
    'thumbsDown' : IDL.Null,
    'none' : IDL.Null,
    'thumbsUp' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'userId' : UserId,
    'role' : MessageRole,
    'feedback' : MessageFeedback,
    'timestamp' : Timestamp,
    'sessionId' : SessionId,
  });
  const SessionSummary = IDL.Record({
    'keyTakeaways' : IDL.Vec(IDL.Text),
    'topic' : IDL.Text,
    'userId' : UserId,
    'durationSeconds' : IDL.Nat,
    'timestamp' : Timestamp,
    'sessionId' : SessionId,
  });
  const SuggestedTopic = IDL.Record({
    'topicName' : IDL.Text,
    'topicId' : TopicId,
    'reason' : IDL.Text,
  });
  const StudentProfileInput = IDL.Record({
    'name' : IDL.Text,
    'gradeLevel' : GradeLevel,
    'preferredSubjects' : IDL.Vec(IDL.Text),
  });
  const SessionSummaryInput = IDL.Record({
    'keyTakeaways' : IDL.Vec(IDL.Text),
    'topic' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'sessionId' : SessionId,
  });
  const SendMessageInput = IDL.Record({
    'content' : IDL.Text,
    'sessionId' : SessionId,
  });
  const QuizAttemptInput = IDL.Record({
    'studentAnswer' : IDL.Text,
    'questionId' : IDL.Nat,
    'sessionId' : SessionId,
    'quizId' : QuizId,
  });
  
  return IDL.Service({
    'addQuizQuestion' : IDL.Func([QuizQuestionInput], [QuizQuestion], []),
    'addTopic' : IDL.Func([TopicInput], [Topic], []),
    'addTopicFact' : IDL.Func([TopicFactInput], [TopicFact], []),
    'getAllMyProgress' : IDL.Func([], [IDL.Vec(TopicProgress)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(StudentProfilePublic)],
        ['query'],
      ),
    'getChatSessionHistory' : IDL.Func([], [IDL.Vec(SessionId)], ['query']),
    'getMyQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getMyTopicProgress' : IDL.Func(
        [TopicId],
        [IDL.Opt(TopicProgress)],
        ['query'],
      ),
    'getPrerequisiteTopics' : IDL.Func([TopicId], [IDL.Vec(Topic)], ['query']),
    'getQuizQuestion' : IDL.Func(
        [QuizId, IDL.Nat],
        [IDL.Opt(QuizQuestion)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func([QuizId], [IDL.Vec(QuizQuestion)], ['query']),
    'getQuizSessionResult' : IDL.Func(
        [SessionId, QuizId],
        [QuizSessionResult],
        ['query'],
      ),
    'getSessionMessages' : IDL.Func(
        [SessionId],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getSessionSummary' : IDL.Func(
        [SessionId],
        [IDL.Opt(SessionSummary)],
        ['query'],
      ),
    'getSuggestedTopics' : IDL.Func([], [IDL.Vec(SuggestedTopic)], ['query']),
    'getTopic' : IDL.Func([TopicId], [IDL.Opt(Topic)], ['query']),
    'getTopicsBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Topic)], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(StudentProfilePublic)],
        ['query'],
      ),
    'getUserSessionSummaries' : IDL.Func(
        [],
        [IDL.Vec(SessionSummary)],
        ['query'],
      ),
    'listTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'recordTopicAttempt' : IDL.Func([TopicId, IDL.Bool], [TopicProgress], []),
    'saveCallerUserProfile' : IDL.Func([StudentProfileInput], [], []),
    'saveSessionSummary' : IDL.Func(
        [SessionSummaryInput],
        [SessionSummary],
        [],
      ),
    'sendMessage' : IDL.Func([SendMessageInput], [ChatMessage], []),
    'setMessageFeedback' : IDL.Func([IDL.Nat, MessageFeedback], [IDL.Bool], []),
    'submitQuizAnswer' : IDL.Func([QuizAttemptInput], [QuizAttempt], []),
  });
};

export const init = ({ IDL }) => { return []; };