/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'userId' : UserId,
  'role' : MessageRole,
  'feedback' : MessageFeedback,
  'timestamp' : Timestamp,
  'sessionId' : SessionId,
}
export type DifficultyLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type GradeLevel = { 'highSchool' : null } |
  { 'elementary' : null } |
  { 'other' : null } |
  { 'middleSchool' : null } |
  { 'college' : null };
export type MasteryLevel = { 'needsWork' : null } |
  { 'mastered' : null } |
  { 'inProgress' : null };
export type MessageFeedback = { 'thumbsDown' : null } |
  { 'none' : null } |
  { 'thumbsUp' : null };
export type MessageRole = { 'ai' : null } |
  { 'student' : null };
export type QuestionType = { 'shortAnswer' : null } |
  { 'multipleChoice' : null };
export interface QuizAttempt {
  'id' : bigint,
  'userId' : UserId,
  'studentAnswer' : string,
  'isCorrect' : boolean,
  'score' : bigint,
  'timestamp' : Timestamp,
  'questionId' : bigint,
  'sessionId' : SessionId,
  'quizId' : QuizId,
}
export interface QuizAttemptInput {
  'studentAnswer' : string,
  'questionId' : bigint,
  'sessionId' : SessionId,
  'quizId' : QuizId,
}
export type QuizId = string;
export interface QuizQuestion {
  'id' : bigint,
  'explanation' : string,
  'correctAnswer' : string,
  'questionText' : string,
  'questionType' : QuestionType,
  'quizId' : QuizId,
  'choices' : Array<string>,
  'topicId' : TopicId,
}
export interface QuizQuestionInput {
  'explanation' : string,
  'correctAnswer' : string,
  'questionText' : string,
  'questionType' : QuestionType,
  'quizId' : QuizId,
  'choices' : Array<string>,
  'topicId' : TopicId,
}
export interface QuizSessionResult {
  'userId' : UserId,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Timestamp,
  'sessionId' : SessionId,
  'correctCount' : bigint,
  'quizId' : QuizId,
}
export interface SendMessageInput {
  'content' : string,
  'sessionId' : SessionId,
}
export type SessionId = string;
export interface SessionSummary {
  'keyTakeaways' : Array<string>,
  'topic' : string,
  'userId' : UserId,
  'durationSeconds' : bigint,
  'timestamp' : Timestamp,
  'sessionId' : SessionId,
}
export interface SessionSummaryInput {
  'keyTakeaways' : Array<string>,
  'topic' : string,
  'durationSeconds' : bigint,
  'sessionId' : SessionId,
}
export interface StudentProfileInput {
  'name' : string,
  'gradeLevel' : GradeLevel,
  'preferredSubjects' : Array<string>,
}
export interface StudentProfilePublic {
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'gradeLevel' : GradeLevel,
  'preferredSubjects' : Array<string>,
}
export interface SuggestedTopic {
  'topicName' : string,
  'topicId' : TopicId,
  'reason' : string,
}
export type Timestamp = bigint;
export interface Topic {
  'id' : TopicId,
  'subject' : string,
  'prerequisites' : Array<TopicId>,
  'difficulty' : DifficultyLevel,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'facts' : Array<TopicFact>,
}
export interface TopicFact {
  'id' : bigint,
  'factText' : string,
  'tags' : Array<string>,
  'topicId' : TopicId,
}
export interface TopicFactInput {
  'factText' : string,
  'tags' : Array<string>,
  'topicId' : TopicId,
}
export type TopicId = string;
export interface TopicInput {
  'id' : TopicId,
  'subject' : string,
  'prerequisites' : Array<TopicId>,
  'difficulty' : DifficultyLevel,
  'name' : string,
  'description' : string,
}
export interface TopicProgress {
  'userId' : UserId,
  'masteryLevel' : MasteryLevel,
  'lastUpdated' : Timestamp,
  'totalAttempts' : bigint,
  'correctCount' : bigint,
  'accuracyPercent' : bigint,
  'topicId' : TopicId,
}
export type UserId = Principal;
export interface _SERVICE {
  'addQuizQuestion' : ActorMethod<[QuizQuestionInput], QuizQuestion>,
  'addTopic' : ActorMethod<[TopicInput], Topic>,
  'addTopicFact' : ActorMethod<[TopicFactInput], TopicFact>,
  'getAllMyProgress' : ActorMethod<[], Array<TopicProgress>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [StudentProfilePublic]>,
  'getChatSessionHistory' : ActorMethod<[], Array<SessionId>>,
  'getMyQuizAttempts' : ActorMethod<[], Array<QuizAttempt>>,
  'getMyTopicProgress' : ActorMethod<[TopicId], [] | [TopicProgress]>,
  'getPrerequisiteTopics' : ActorMethod<[TopicId], Array<Topic>>,
  'getQuizQuestion' : ActorMethod<[QuizId, bigint], [] | [QuizQuestion]>,
  'getQuizQuestions' : ActorMethod<[QuizId], Array<QuizQuestion>>,
  'getQuizSessionResult' : ActorMethod<[SessionId, QuizId], QuizSessionResult>,
  'getSessionMessages' : ActorMethod<[SessionId], Array<ChatMessage>>,
  'getSessionSummary' : ActorMethod<[SessionId], [] | [SessionSummary]>,
  'getSuggestedTopics' : ActorMethod<[], Array<SuggestedTopic>>,
  'getTopic' : ActorMethod<[TopicId], [] | [Topic]>,
  'getTopicsBySubject' : ActorMethod<[string], Array<Topic>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [StudentProfilePublic]>,
  'getUserSessionSummaries' : ActorMethod<[], Array<SessionSummary>>,
  'listTopics' : ActorMethod<[], Array<Topic>>,
  'recordTopicAttempt' : ActorMethod<[TopicId, boolean], TopicProgress>,
  'saveCallerUserProfile' : ActorMethod<[StudentProfileInput], undefined>,
  'saveSessionSummary' : ActorMethod<[SessionSummaryInput], SessionSummary>,
  'sendMessage' : ActorMethod<[SendMessageInput], ChatMessage>,
  'setMessageFeedback' : ActorMethod<[bigint, MessageFeedback], boolean>,
  'submitQuizAnswer' : ActorMethod<[QuizAttemptInput], QuizAttempt>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];