/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface QuizQuestion {
    id: bigint;
    explanation: string;
    correctAnswer: string;
    questionText: string;
    questionType: QuestionType;
    quizId: QuizId;
    choices: Array<string>;
    topicId: TopicId;
}
export interface TopicFact {
    id: bigint;
    factText: string;
    tags: Array<string>;
    topicId: TopicId;
}
export interface SuggestedTopic {
    topicName: string;
    topicId: TopicId;
    reason: string;
}
export type TopicId = string;
export interface StudentProfileInput {
    name: string;
    gradeLevel: GradeLevel;
    preferredSubjects: Array<string>;
}
export interface QuizQuestionInput {
    explanation: string;
    correctAnswer: string;
    questionText: string;
    questionType: QuestionType;
    quizId: QuizId;
    choices: Array<string>;
    topicId: TopicId;
}
export interface QuizAttempt {
    id: bigint;
    userId: UserId;
    studentAnswer: string;
    isCorrect: boolean;
    score: bigint;
    timestamp: Timestamp;
    questionId: bigint;
    sessionId: SessionId;
    quizId: QuizId;
}
export interface QuizSessionResult {
    userId: UserId;
    score: bigint;
    totalQuestions: bigint;
    timestamp: Timestamp;
    sessionId: SessionId;
    correctCount: bigint;
    quizId: QuizId;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    userId: UserId;
    role: MessageRole;
    feedback: MessageFeedback;
    timestamp: Timestamp;
    sessionId: SessionId;
}
export interface SendMessageInput {
    content: string;
    sessionId: SessionId;
}
export interface SessionSummaryInput {
    keyTakeaways: Array<string>;
    topic: string;
    durationSeconds: bigint;
    sessionId: SessionId;
}
export interface StudentProfilePublic {
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    gradeLevel: GradeLevel;
    preferredSubjects: Array<string>;
}
export interface TopicInput {
    id: TopicId;
    subject: string;
    prerequisites: Array<TopicId>;
    difficulty: DifficultyLevel;
    name: string;
    description: string;
}
export type SessionId = string;
export type UserId = Principal;
export interface SessionSummary {
    keyTakeaways: Array<string>;
    topic: string;
    userId: UserId;
    durationSeconds: bigint;
    timestamp: Timestamp;
    sessionId: SessionId;
}
export interface TopicFactInput {
    factText: string;
    tags: Array<string>;
    topicId: TopicId;
}
export interface Topic {
    id: TopicId;
    subject: string;
    prerequisites: Array<TopicId>;
    difficulty: DifficultyLevel;
    name: string;
    createdAt: Timestamp;
    description: string;
    facts: Array<TopicFact>;
}
export interface TopicProgress {
    userId: UserId;
    masteryLevel: MasteryLevel;
    lastUpdated: Timestamp;
    totalAttempts: bigint;
    correctCount: bigint;
    accuracyPercent: bigint;
    topicId: TopicId;
}
export interface QuizAttemptInput {
    studentAnswer: string;
    questionId: bigint;
    sessionId: SessionId;
    quizId: QuizId;
}
export type QuizId = string;
export enum DifficultyLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum GradeLevel {
    highSchool = "highSchool",
    elementary = "elementary",
    other = "other",
    middleSchool = "middleSchool",
    college = "college"
}
export enum MasteryLevel {
    needsWork = "needsWork",
    mastered = "mastered",
    inProgress = "inProgress"
}
export enum MessageFeedback {
    thumbsDown = "thumbsDown",
    none = "none",
    thumbsUp = "thumbsUp"
}
export enum MessageRole {
    ai = "ai",
    student = "student"
}
export enum QuestionType {
    shortAnswer = "shortAnswer",
    multipleChoice = "multipleChoice"
}
export interface backendInterface {
    addQuizQuestion(input: QuizQuestionInput): Promise<QuizQuestion>;
    addTopic(input: TopicInput): Promise<Topic>;
    addTopicFact(input: TopicFactInput): Promise<TopicFact>;
    getAllMyProgress(): Promise<Array<TopicProgress>>;
    getCallerUserProfile(): Promise<StudentProfilePublic | null>;
    getChatSessionHistory(): Promise<Array<SessionId>>;
    getMyQuizAttempts(): Promise<Array<QuizAttempt>>;
    getMyTopicProgress(topicId: TopicId): Promise<TopicProgress | null>;
    getPrerequisiteTopics(topicId: TopicId): Promise<Array<Topic>>;
    getQuizQuestion(quizId: QuizId, questionId: bigint): Promise<QuizQuestion | null>;
    getQuizQuestions(quizId: QuizId): Promise<Array<QuizQuestion>>;
    getQuizSessionResult(sessionId: SessionId, quizId: QuizId): Promise<QuizSessionResult>;
    getSessionMessages(sessionId: SessionId): Promise<Array<ChatMessage>>;
    getSessionSummary(sessionId: SessionId): Promise<SessionSummary | null>;
    getSuggestedTopics(): Promise<Array<SuggestedTopic>>;
    getTopic(topicId: TopicId): Promise<Topic | null>;
    getTopicsBySubject(subject: string): Promise<Array<Topic>>;
    getUserProfile(userId: UserId): Promise<StudentProfilePublic | null>;
    getUserSessionSummaries(): Promise<Array<SessionSummary>>;
    listTopics(): Promise<Array<Topic>>;
    recordTopicAttempt(topicId: TopicId, isCorrect: boolean): Promise<TopicProgress>;
    saveCallerUserProfile(input: StudentProfileInput): Promise<void>;
    saveSessionSummary(input: SessionSummaryInput): Promise<SessionSummary>;
    sendMessage(input: SendMessageInput): Promise<ChatMessage>;
    setMessageFeedback(messageId: bigint, feedback: MessageFeedback): Promise<boolean>;
    submitQuizAnswer(input: QuizAttemptInput): Promise<QuizAttempt>;
}
import type { ChatMessage as _ChatMessage, DifficultyLevel as _DifficultyLevel, GradeLevel as _GradeLevel, MasteryLevel as _MasteryLevel, MessageFeedback as _MessageFeedback, MessageRole as _MessageRole, QuestionType as _QuestionType, QuizId as _QuizId, QuizQuestion as _QuizQuestion, QuizQuestionInput as _QuizQuestionInput, SessionId as _SessionId, SessionSummary as _SessionSummary, StudentProfileInput as _StudentProfileInput, StudentProfilePublic as _StudentProfilePublic, Timestamp as _Timestamp, Topic as _Topic, TopicFact as _TopicFact, TopicId as _TopicId, TopicInput as _TopicInput, TopicProgress as _TopicProgress, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addQuizQuestion(arg0: QuizQuestionInput): Promise<QuizQuestion> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuizQuestion(to_candid_QuizQuestionInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_QuizQuestion_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuizQuestion(to_candid_QuizQuestionInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_QuizQuestion_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTopic(arg0: TopicInput): Promise<Topic> {
        if (this.processError) {
            try {
                const result = await this.actor.addTopic(to_candid_TopicInput_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Topic_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTopic(to_candid_TopicInput_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Topic_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTopicFact(arg0: TopicFactInput): Promise<TopicFact> {
        if (this.processError) {
            try {
                const result = await this.actor.addTopicFact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTopicFact(arg0);
            return result;
        }
    }
    async getAllMyProgress(): Promise<Array<TopicProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMyProgress();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMyProgress();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<StudentProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatSessionHistory(): Promise<Array<SessionId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatSessionHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatSessionHistory();
            return result;
        }
    }
    async getMyQuizAttempts(): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizAttempts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizAttempts();
            return result;
        }
    }
    async getMyTopicProgress(arg0: TopicId): Promise<TopicProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTopicProgress(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTopicProgress(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrerequisiteTopics(arg0: TopicId): Promise<Array<Topic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrerequisiteTopics(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrerequisiteTopics(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestion(arg0: QuizId, arg1: bigint): Promise<QuizQuestion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestion(arg0, arg1);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestion(arg0, arg1);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestions(arg0: QuizId): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizSessionResult(arg0: SessionId, arg1: QuizId): Promise<QuizSessionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizSessionResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizSessionResult(arg0, arg1);
            return result;
        }
    }
    async getSessionMessages(arg0: SessionId): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionMessages(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionMessages(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionSummary(arg0: SessionId): Promise<SessionSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionSummary(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionSummary(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuggestedTopics(): Promise<Array<SuggestedTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestedTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestedTopics();
            return result;
        }
    }
    async getTopic(arg0: TopicId): Promise<Topic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopic(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopic(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopicsBySubject(arg0: string): Promise<Array<Topic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopicsBySubject(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopicsBySubject(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<StudentProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSessionSummaries(): Promise<Array<SessionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSessionSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSessionSummaries();
            return result;
        }
    }
    async listTopics(): Promise<Array<Topic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTopics();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTopics();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordTopicAttempt(arg0: TopicId, arg1: boolean): Promise<TopicProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTopicAttempt(arg0, arg1);
                return from_candid_TopicProgress_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTopicAttempt(arg0, arg1);
            return from_candid_TopicProgress_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: StudentProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_StudentProfileInput_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_StudentProfileInput_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveSessionSummary(arg0: SessionSummaryInput): Promise<SessionSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSessionSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSessionSummary(arg0);
            return result;
        }
    }
    async sendMessage(arg0: SendMessageInput): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return from_candid_ChatMessage_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return from_candid_ChatMessage_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async setMessageFeedback(arg0: bigint, arg1: MessageFeedback): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setMessageFeedback(arg0, to_candid_MessageFeedback_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMessageFeedback(arg0, to_candid_MessageFeedback_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitQuizAnswer(arg0: QuizAttemptInput): Promise<QuizAttempt> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAnswer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAnswer(arg0);
            return result;
        }
    }
}
function from_candid_ChatMessage_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_DifficultyLevel_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyLevel): DifficultyLevel {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_GradeLevel_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GradeLevel): GradeLevel {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MasteryLevel_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MasteryLevel): MasteryLevel {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_MessageFeedback_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageFeedback): MessageFeedback {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_MessageRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_QuizQuestion_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizQuestion): QuizQuestion {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProfilePublic_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfilePublic): StudentProfilePublic {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TopicProgress_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopicProgress): TopicProgress {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Topic_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Topic): Topic {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfilePublic]): StudentProfilePublic | null {
    return value.length === 0 ? null : from_candid_StudentProfilePublic_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TopicProgress]): TopicProgress | null {
    return value.length === 0 ? null : from_candid_TopicProgress_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizQuestion]): QuizQuestion | null {
    return value.length === 0 ? null : from_candid_QuizQuestion_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionSummary]): SessionSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Topic]): Topic | null {
    return value.length === 0 ? null : from_candid_Topic_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TopicId;
    subject: string;
    prerequisites: Array<_TopicId>;
    difficulty: _DifficultyLevel;
    name: string;
    createdAt: _Timestamp;
    description: string;
    facts: Array<_TopicFact>;
}): {
    id: TopicId;
    subject: string;
    prerequisites: Array<TopicId>;
    difficulty: DifficultyLevel;
    name: string;
    createdAt: Timestamp;
    description: string;
    facts: Array<TopicFact>;
} {
    return {
        id: value.id,
        subject: value.subject,
        prerequisites: value.prerequisites,
        difficulty: from_candid_DifficultyLevel_n15(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        facts: value.facts
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    masteryLevel: _MasteryLevel;
    lastUpdated: _Timestamp;
    totalAttempts: bigint;
    correctCount: bigint;
    accuracyPercent: bigint;
    topicId: _TopicId;
}): {
    userId: UserId;
    masteryLevel: MasteryLevel;
    lastUpdated: Timestamp;
    totalAttempts: bigint;
    correctCount: bigint;
    accuracyPercent: bigint;
    topicId: TopicId;
} {
    return {
        userId: value.userId,
        masteryLevel: from_candid_MasteryLevel_n20(_uploadFile, _downloadFile, value.masteryLevel),
        lastUpdated: value.lastUpdated,
        totalAttempts: value.totalAttempts,
        correctCount: value.correctCount,
        accuracyPercent: value.accuracyPercent,
        topicId: value.topicId
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    name: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    gradeLevel: _GradeLevel;
    preferredSubjects: Array<string>;
}): {
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    gradeLevel: GradeLevel;
    preferredSubjects: Array<string>;
} {
    return {
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        gradeLevel: from_candid_GradeLevel_n25(_uploadFile, _downloadFile, value.gradeLevel),
        preferredSubjects: value.preferredSubjects
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    userId: _UserId;
    role: _MessageRole;
    feedback: _MessageFeedback;
    timestamp: _Timestamp;
    sessionId: _SessionId;
}): {
    id: bigint;
    content: string;
    userId: UserId;
    role: MessageRole;
    feedback: MessageFeedback;
    timestamp: Timestamp;
    sessionId: SessionId;
} {
    return {
        id: value.id,
        content: value.content,
        userId: value.userId,
        role: from_candid_MessageRole_n34(_uploadFile, _downloadFile, value.role),
        feedback: from_candid_MessageFeedback_n36(_uploadFile, _downloadFile, value.feedback),
        timestamp: value.timestamp,
        sessionId: value.sessionId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    explanation: string;
    correctAnswer: string;
    questionText: string;
    questionType: _QuestionType;
    quizId: _QuizId;
    choices: Array<string>;
    topicId: _TopicId;
}): {
    id: bigint;
    explanation: string;
    correctAnswer: string;
    questionText: string;
    questionType: QuestionType;
    quizId: QuizId;
    choices: Array<string>;
    topicId: TopicId;
} {
    return {
        id: value.id,
        explanation: value.explanation,
        correctAnswer: value.correctAnswer,
        questionText: value.questionText,
        questionType: from_candid_QuestionType_n7(_uploadFile, _downloadFile, value.questionType),
        quizId: value.quizId,
        choices: value.choices,
        topicId: value.topicId
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): DifficultyLevel {
    return "intermediate" in value ? DifficultyLevel.intermediate : "beginner" in value ? DifficultyLevel.beginner : "advanced" in value ? DifficultyLevel.advanced : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    needsWork: null;
} | {
    mastered: null;
} | {
    inProgress: null;
}): MasteryLevel {
    return "needsWork" in value ? MasteryLevel.needsWork : "mastered" in value ? MasteryLevel.mastered : "inProgress" in value ? MasteryLevel.inProgress : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    highSchool: null;
} | {
    elementary: null;
} | {
    other: null;
} | {
    middleSchool: null;
} | {
    college: null;
}): GradeLevel {
    return "highSchool" in value ? GradeLevel.highSchool : "elementary" in value ? GradeLevel.elementary : "other" in value ? GradeLevel.other : "middleSchool" in value ? GradeLevel.middleSchool : "college" in value ? GradeLevel.college : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ai: null;
} | {
    student: null;
}): MessageRole {
    return "ai" in value ? MessageRole.ai : "student" in value ? MessageRole.student : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    thumbsDown: null;
} | {
    none: null;
} | {
    thumbsUp: null;
}): MessageFeedback {
    return "thumbsDown" in value ? MessageFeedback.thumbsDown : "none" in value ? MessageFeedback.none : "thumbsUp" in value ? MessageFeedback.thumbsUp : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shortAnswer: null;
} | {
    multipleChoice: null;
}): QuestionType {
    return "shortAnswer" in value ? QuestionType.shortAnswer : "multipleChoice" in value ? QuestionType.multipleChoice : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TopicProgress>): Array<TopicProgress> {
    return value.map((x)=>from_candid_TopicProgress_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Topic>): Array<Topic> {
    return value.map((x)=>from_candid_Topic_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizQuestion>): Array<QuizQuestion> {
    return value.map((x)=>from_candid_QuizQuestion_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n32(_uploadFile, _downloadFile, x));
}
function to_candid_DifficultyLevel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): _DifficultyLevel {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_GradeLevel_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GradeLevel): _GradeLevel {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_MessageFeedback_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageFeedback): _MessageFeedback {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_QuizQuestionInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizQuestionInput): _QuizQuestionInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_StudentProfileInput_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentProfileInput): _StudentProfileInput {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_TopicInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TopicInput): _TopicInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TopicId;
    subject: string;
    prerequisites: Array<TopicId>;
    difficulty: DifficultyLevel;
    name: string;
    description: string;
}): {
    id: _TopicId;
    subject: string;
    prerequisites: Array<_TopicId>;
    difficulty: _DifficultyLevel;
    name: string;
    description: string;
} {
    return {
        id: value.id,
        subject: value.subject,
        prerequisites: value.prerequisites,
        difficulty: to_candid_DifficultyLevel_n11(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        description: value.description
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    explanation: string;
    correctAnswer: string;
    questionText: string;
    questionType: QuestionType;
    quizId: QuizId;
    choices: Array<string>;
    topicId: TopicId;
}): {
    explanation: string;
    correctAnswer: string;
    questionText: string;
    questionType: _QuestionType;
    quizId: _QuizId;
    choices: Array<string>;
    topicId: _TopicId;
} {
    return {
        explanation: value.explanation,
        correctAnswer: value.correctAnswer,
        questionText: value.questionText,
        questionType: to_candid_QuestionType_n3(_uploadFile, _downloadFile, value.questionType),
        quizId: value.quizId,
        choices: value.choices,
        topicId: value.topicId
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    gradeLevel: GradeLevel;
    preferredSubjects: Array<string>;
}): {
    name: string;
    gradeLevel: _GradeLevel;
    preferredSubjects: Array<string>;
} {
    return {
        name: value.name,
        gradeLevel: to_candid_GradeLevel_n42(_uploadFile, _downloadFile, value.gradeLevel),
        preferredSubjects: value.preferredSubjects
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == DifficultyLevel.intermediate ? {
        intermediate: null
    } : value == DifficultyLevel.beginner ? {
        beginner: null
    } : value == DifficultyLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    shortAnswer: null;
} | {
    multipleChoice: null;
} {
    return value == QuestionType.shortAnswer ? {
        shortAnswer: null
    } : value == QuestionType.multipleChoice ? {
        multipleChoice: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GradeLevel): {
    highSchool: null;
} | {
    elementary: null;
} | {
    other: null;
} | {
    middleSchool: null;
} | {
    college: null;
} {
    return value == GradeLevel.highSchool ? {
        highSchool: null
    } : value == GradeLevel.elementary ? {
        elementary: null
    } : value == GradeLevel.other ? {
        other: null
    } : value == GradeLevel.middleSchool ? {
        middleSchool: null
    } : value == GradeLevel.college ? {
        college: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageFeedback): {
    thumbsDown: null;
} | {
    none: null;
} | {
    thumbsUp: null;
} {
    return value == MessageFeedback.thumbsDown ? {
        thumbsDown: null
    } : value == MessageFeedback.none ? {
        none: null
    } : value == MessageFeedback.thumbsUp ? {
        thumbsUp: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
